apiVersion: v1
kind: Service
metadata:
  name: myapp1-lb-service
  labels:
    app: myapp1
spec:
  type: LoadBalancer
  selector:
    app: myapp1
  ports:
  - name: http
    port: 80
    targetPort: 8080